apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
  # openshift specific, uncomment this component if on openshift clusters
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: openshift/openshift-scc/base
  #   name: openshift-scc
  # istio related components
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/istio-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/add-anonymous-user-filter
    name: add-anonymous-user-filter
  # application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  # cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/cert-manager
    name: cert-manager
  # metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/application/metadata
    name: metadata
  # kubeflow apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/base
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/components/tektoncd
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/ibm/components/kfp-tekton
    name: kubeflow-apps
  repos:
  - name: manifests
    uri: https://github.com/adrian555/manifests/archive/update-manifests-repo-link.tar.gz
  version: master
